archive-format key of custom target specs is required
Since commit https://github.com/rust-lang/rust/commit/3f36f7a980465055cafbbbd2b9109dadbb55fd03
the archive-format key of custom target specs is now required, otherwise Rust
complains with:

```
/home/joerg/rust-cross-libs/rust/bin/rustc src/libcore/lib.rs -C opt-level=2 --target=armv5te-unknown-linux-musl -L /home/joerg/rust-cross-libs/build --out-dir=/home/joerg/rust-cross-libs/build -C extra-filename=-8102e29f
error: Don't know how to build archive of type:
```

Adding "gnu" solves this issue.

Closes: https://github.com/rust-lang/rust/issues/34429